apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: nginx
    env: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        env: production
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: starbigwednesdayio
      containers:
      - name: nginxhttps
        image: gcr.io/first-footing-108508/nginx-api-proxy:7fdbd51
        ports:
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
