apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
    env: production
spec:
  ports:
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: nginx
    env: production
  type: LoadBalancer
